eakmanrq/sqlframe

- sqlframe/base/session.py
- sqlframe/duckdb/readwriter.py
- tests/fixtures/employee_extra_line.csv
- tests/integration/engines/duck/test_duckdb_reader.py
Addressing issues discussed here: https://github.com/eakmanrq/sqlframe/issues/11
> feat: improve DuckDB csv reading support

- sqlframe/base/dataframe.py
- tests/unit/standalone/test_dataframe.py
Helps resolve this issue: https://github.com/eakmanrq/sqlframe/issues/11
> fix: properly alias with column overlapping name

- Makefile
- setup.py
- sqlframe/base/mixins/catalog_mixins.py
- sqlframe/base/mixins/readwriter_mixins.py
- sqlframe/base/session.py
- sqlframe/base/util.py
- sqlframe/spark/session.py
Makes pandas an optional dependency and if someone tries to use pandas without having it installed then they will get an error. 
Resolves: https://github.com/eakmanrq/sqlframe/issues/12
> feat: make pandas optional dependency

- Makefile
- sqlframe/base/column.py
- sqlframe/base/dataframe.py
- sqlframe/base/decorators.py
- sqlframe/base/readerwriter.py
- sqlframe/base/session.py
- sqlframe/base/util.py
- sqlframe/snowflake/catalog.py
- tests/integration/engines/snowflake/test_snowflake_session.py
- tests/unit/standalone/test_session.py
- tests/unit/test_util.py
Found some gaps in current normalization coverage which was causing issues with Snowflake since we would end up comparing a non-normalized column (lowercase) to normalized columns (uppercase for Snowflake). This fixes all the issues found. 
Related to: https://github.com/eakmanrq/sqlframe/issues/31
> fix: improve normalization

- docs/configuration.md
- sqlframe/base/dataframe.py
Improve the options to allow different modes and changing the prompt. 
Video: https://www.loom.com/share/4055e86dafdd406283d7ba0e0656f0c9?sid=debfb6a4-f8c1-44e5-859a-dbf6dae49a12
> feat: Improve OpenAI support

- setup.py
Fix typo in: https://github.com/eakmanrq/sqlframe/pull/40
> fix: fix typo including typed files

- sqlframe/base/column.py
- tests/unit/standalone/test_dataframe.py
Related to: https://github.com/eakmanrq/sqlframe/issues/45
> chore: improve error handling missing dataframe method

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Prior to this if doing a full outer join the left column was just chosen when really it should be a coalesce of the left and right for all of the join columns. 
Related to: https://github.com/eakmanrq/sqlframe/issues/51
> fix: coalesce columns in full outer join

- sqlframe/base/column.py
- tests/unit/standalone/test_column.py
Fixes: https://github.com/eakmanrq/sqlframe/issues/74
> fix: make not paren expression being negated

- sqlframe/base/functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/92
> feat: make contains available more engines

- sqlframe/base/column.py
- sqlframe/base/function_alternatives.py
- tests/integration/engines/test_engine_column.py
- tests/unit/standalone/test_column.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/90
> feat: add getItem support

- sqlframe/base/dataframe.py
- sqlframe/base/types.py
- sqlframe/bigquery/functions.py
- tests/integration/engines/test_engine_dataframe.py
- tests/integration/test_int_dataframe.py
- tests/unit/standalone/test_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/88
> fix: expand star in select expressions

- sqlframe/base/function_alternatives.py
- sqlframe/base/functions.py
- sqlframe/bigquery/functions.py
- sqlframe/duckdb/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/100
> feat: add array_append support all engines

- sqlframe/base/column.py
- sqlframe/base/function_alternatives.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/99
> feat: treat strings a lit when doing binary_ops

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Fixes: https://github.com/eakmanrq/sqlframe/issues/102
> fix: correctly replace column after join on 0 index

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Fixes: https://github.com/eakmanrq/sqlframe/issues/103
> fix: correctly handle chained joins shared join column

- docs/duckdb.md
- docs/postgres.md
- sqlframe/base/functions.py
- sqlframe/duckdb/functions.py
- sqlframe/postgres/functions.py
> feat: add last_day to all engines

- sqlframe/base/dataframe.py
- tests/integration/engines/duck/test_duckdb_dataframe.py
- tests/unit/standalone/test_dataframe.py
- tests/unit/standalone/test_session.py
Fixes: #112 
May want to consider making this optional in the future but just going to always do it for now.
> fix: always quote identifiers

- sqlframe/base/dataframe.py
- sqlframe/base/session.py
- sqlframe/duckdb/dataframe.py
- sqlframe/duckdb/session.py
- sqlframe/postgres/session.py
- sqlframe/spark/session.py
- tests/integration/engines/duck/test_duckdb_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/54
> feat: add toArrow support DuckDB

- docs/bigquery.md
- docs/duckdb.md
- docs/postgres.md
- docs/snowflake.md
- docs/spark.md
- docs/standalone.md
- sqlframe/base/dataframe.py
- tests/unit/standalone/test_dataframe.py
Request: https://github.com/eakmanrq/sqlframe/issues/138
Starts with the low effort/high ROI approach of directly implementing what SQLGlot. Some obvious improvements would be to provide interactive CLL for all columns and improving the generated HTML. Please open feature requests if you specifically want one of these features. It would likely make more sense to add that support to SQLGlot itself instead of this library.
> feat: add lineage support

- sqlframe/duckdb/readwriter.py
> feat: add delta format read in Duckdb

- docs/bigquery.md
- docs/duckdb.md
- docs/snowflake.md
- setup.py
- sqlframe/base/functions.py
- sqlframe/bigquery/functions.pyi
- sqlframe/duckdb/functions.pyi
- sqlframe/snowflake/functions.pyi
- sqlframe/spark/functions.py
- sqlframe/spark/functions.pyi
- tests/unit/standalone/test_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/pull/179
> feat: add overlay and substr support

- sqlframe/base/util.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/201
> fix: handle timestamp_ns duckdb type

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/210
> fix: resolve self-join issue

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
> fix: make self-join logic more flexible

- sqlframe/base/column.py
- tests/unit/standalone/test_column.py
- tests/unit/standalone/test_functions.py
Fixes: https://github.com/eakmanrq/sqlframe/issues/224
> fix: put boolean in paren

- sqlframe/base/dataframe.py
- sqlframe/base/decorators.py
- sqlframe/base/mixins/dataframe_mixins.py
- sqlframe/base/operations.py
- sqlframe/base/session.py
- sqlframe/bigquery/dataframe.py
- sqlframe/databricks/dataframe.py
- sqlframe/duckdb/dataframe.py
- sqlframe/postgres/dataframe.py
- sqlframe/redshift/dataframe.py
- sqlframe/snowflake/dataframe.py
- sqlframe/spark/dataframe.py
- sqlframe/standalone/dataframe.py
- sqlframe/testing/utils.py
- tests/integration/engines/test_engine_dataframe.py
- tests/integration/engines/test_engine_writer.py
- tests/integration/engines/test_int_functions.py
- tests/integration/fixtures.py
- tests/integration/test_int_dataframe.py
- tests/integration/test_int_dataframe_stats.py
> feat!: make base dataframe class public

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Fixes https://github.com/eakmanrq/sqlframe/issues/232
> fix: remove alias from where

- docs/spark.md
Related to: https://github.com/eakmanrq/sqlframe/issues/236
> fix: remove activate from spark docs

- setup.py
- tests/unit/standalone/test_session_case_sensitivity.py
Deprecates: https://github.com/eakmanrq/sqlframe/pull/237
> feat: add sqlglot 26.2.0 support

- sqlframe/base/dataframe.py
- sqlframe/bigquery/dataframe.py
- sqlframe/duckdb/dataframe.py
- sqlframe/snowflake/dataframe.py
- tests/integration/engines/bigquery/test_bigquery_dataframe.py
- tests/integration/engines/databricks/test_databricks_dataframe.py
- tests/integration/engines/duck/test_duckdb_dataframe.py
- tests/integration/engines/postgres/test_postgres_dataframe.py
- tests/integration/engines/snowflake/test_snowflake_dataframe.py
- tests/integration/engines/spark/test_spark_dataframe.py
Forgot to write tests for explain when it was added so implementation was improved and tested across engines. 
Helps with: https://github.com/eakmanrq/sqlframe/issues/242
> fix: properly implement and test explain

- sqlframe/base/session.py
- tests/integration/engines/duck/test_duckdb_reader.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/242
> fix: infer schema after read parquet

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/244
> fix: right join and union cte

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
> fix: change counter on duplicate cte to random id

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/264
> fix!: have dayofweek match pyspark

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
- tests/unit/standalone/test_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/265
> feat: support float infinity

- docs/bigquery.md
- docs/duckdb.md
- docs/postgres.md
- docs/snowflake.md
- sqlframe/base/functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/260
> feat: add replace support

- docs/bigquery.md
- docs/duckdb.md
- docs/postgres.md
- docs/snowflake.md
- sqlframe/base/functions.py
- tests/unit/standalone/test_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/261
> feat: support char length

- sqlframe/base/session.py
- tests/integration/engines/bigquery/test_bigquery_session.py
- tests/integration/engines/databricks/test_databricks_session.py
- tests/integration/engines/duck/test_duckdb_session.py
- tests/integration/engines/postgres/test_postgres_session.py
- tests/integration/engines/redshift/test_redshift_session.py
- tests/integration/engines/snowflake/test_snowflake_session.py
Helps with: https://github.com/eakmanrq/sqlframe/issues/262
> feat: add execution dialect name

- sqlframe/base/decorators.py
> fix: address Python 3.12 deprecation warning

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/277
> fix: handle ambiguous columns after filter

- docs/bigquery.md
- docs/duckdb.md
- docs/postgres.md
- docs/snowflake.md
- sqlframe/base/functions.py
- tests/unit/standalone/test_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/275
> feat: add btrim support

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/281
> fix: handle unresolvable ambiguous column

- sqlframe/base/dataframe.py
- sqlframe/base/session.py
- tests/unit/standalone/test_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/286
> feat: add support for unquoted identifiers in sql

- sqlframe/base/dataframe.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/289
> fix: full outer coalesce bug

- docs/bigquery.md
- docs/duckdb.md
- docs/postgres.md
- docs/snowflake.md
- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
- tests/unit/standalone/test_functions.py
Related to: https://github.com/eakmanrq/sqlframe/issues/292
> feat: add array size support

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/293
> fix: improve unix micros

- docs/bigquery.md
- docs/duckdb.md
- docs/postgres.md
- docs/snowflake.md
- sqlframe/base/functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/292
> feat: add to_timestamp_ntz support

- sqlframe/base/session.py
- tests/integration/engines/test_engine_dataframe.py
- tests/unit/standalone/test_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/294
> fix: capture display name createDataFrame

- sqlframe/base/session.py
- sqlframe/spark/session.py
- tests/integration/engines/test_engine_dataframe.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/291
> fix: remove backticks from column names

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/303
> fix: day in duckdb

- sqlframe/base/util.py
- tests/integration/engines/test_engine_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/291
> fix: don't normalize schema column names if provided

- sqlframe/base/dataframe.py
- tests/integration/engines/test_engine_dataframe.py
- tests/unit/standalone/test_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/294
> fix: use display name df columns

- sqlframe/base/dataframe.py
- tests/integration/engines/databricks/test_databricks_dataframe.py
- tests/integration/engines/duck/test_duckdb_dataframe.py
- tests/integration/engines/postgres/test_postgres_dataframe.py
- tests/integration/engines/test_engine_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/291
> fix: use display name schema printSchema

- sqlframe/base/window.py
- tests/integration/test_int_dataframe.py
- tests/unit/standalone/test_column.py
- tests/unit/standalone/test_window.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/317
> fix: rowsBetween negative values

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
- tests/unit/standalone/test_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/321
> feat: maintain alias in structs

- sqlframe/base/catalog.py
- sqlframe/base/mixins/catalog_mixins.py
- sqlframe/base/readerwriter.py
- sqlframe/bigquery/catalog.py
- sqlframe/databricks/catalog.py
- sqlframe/databricks/readwriter.py
- sqlframe/duckdb/catalog.py
- sqlframe/postgres/catalog.py
- sqlframe/redshift/catalog.py
- sqlframe/snowflake/catalog.py
- sqlframe/spark/catalog.py
- sqlframe/standalone/catalog.py
- tests/integration/engines/test_engine_reader.py
- tests/integration/engines/test_engine_writer.py
- tests/integration/fixtures.py
Hi,
Following this PR https://github.com/eakmanrq/sqlframe/pull/287 and this issue https://github.com/eakmanrq/sqlframe/issues/266 I'm now adding the same capabilities to the databricks backend.
> feat: use native databricks reader and writer

- docs/configuration.md
- sqlframe/__init__.py
- tests/unit/test_activate.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/333
> feat: add activate context manager

- sqlframe/base/column.py
- tests/integration/engines/test_engine_column.py
Resolve: https://github.com/eakmanrq/sqlframe/issues/332
> feat: add support for getField and accessing column attr

- sqlframe/base/readerwriter.py
- sqlframe/databricks/readwriter.py
- sqlframe/duckdb/readwriter.py
- sqlframe/spark/readwriter.py
- tests/unit/duck/test_reader_options.py
- tests/unit/spark/test_reader_options.py
- tests/unit/test_base_reader_options.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/341
> feat: add options to dataframe reader

- docs/duckdb.md
- sqlframe/base/functions.py
- sqlframe/duckdb/functions.pyi
Resolves: https://github.com/eakmanrq/sqlframe/issues/348
> feat: add product support duckdb

- sqlframe/base/session.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/346
> fix: add kwargs to range

- sqlframe/base/dataframe.py
- sqlframe/base/group.py
- tests/integration/test_int_dataframe.py
- tests/unit/standalone/test_dataframe.py
Addresses some of the issues in: https://github.com/eakmanrq/sqlframe/issues/356
> fix: various fixes related to group by

- sqlframe/base/dataframe.py
- tests/integration/engines/test_engine_dataframe.py
Resolves https://github.com/eakmanrq/sqlframe/issues/364
> feat: support chaining limit calls

- docs/databricks.md
- setup.py
- sqlframe/databricks/dataframe.py
- tests/integration/engines/databricks/test_databricks_dataframe.py
Requested in https://github.com/eakmanrq/sqlframe/issues/54
> feat: support toArrow in Databricks engine

- docs/duckdb.md
- sqlframe/base/functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/371
> feat: add last_value support

- sqlframe/base/column.py
- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/374
> fix: last_value as window func for duckdb

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/376
> feat: first_value support with window func

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Fixes: https://github.com/eakmanrq/sqlframe/issues/386
> fix: skewness for duckdb

- .gitignore
- sqlframe/base/session.py
- sqlframe/base/util.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/325
Resolves: https://github.com/eakmanrq/sqlframe/issues/326
> fix: add test for timestamp timezone

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/389
> fix: skewness use count col

- sqlframe/base/dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/390
> feat: add repr and _display_ support

- sqlframe/base/dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/393
> fix: revert repr change

- sqlframe/base/catalog.py
- sqlframe/base/util.py
- tests/unit/test_catalog.py
- tests/unit/test_util.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/394
> feat: support spark types in add_table dictionary

- sqlframe/base/session.py
- tests/integration/engines/duck/test_duckdb_dataframe.py
- tests/integration/engines/spark/test_spark_dataframe.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/383
> fix: properly differentiate tzinfo datetime objects

- docs/bigquery.md
- docs/duckdb.md
- docs/snowflake.md
- sqlframe/base/column.py
- sqlframe/base/functions.py
- tests/integration/engines/test_engine_column.py
- tests/integration/engines/test_int_functions.py
- tests/unit/standalone/test_column.py
Fully resolves: https://github.com/eakmanrq/sqlframe/issues/92
> feat: add contains column method

- sqlframe/base/types.py
- tests/unit/standalone/test_types.py
> refactor: define integer type string names in simpleString

- docs/snowflake.md
- sqlframe/base/group.py
- tests/integration/test_int_grouped_data.py
Related to: https://github.com/eakmanrq/sqlframe/issues/430
> feat: add pivot support

- sqlframe/base/mixins/table_mixins.py
Resolves: #428 
Note that I added the `type: ignore` directive for the return type of the decorator. I initially went down the route of using [Concatenate](https://docs.python.org/3/library/typing.html#typing.Concatenate), but that did not produce the desirable type hinting:
(notice how it thinks the first argument is `condition` rather than `other_df`).
> refactor: update `ensure_cte` function signature to use ParamSpec

- sqlframe/base/group.py
- tests/integration/test_int_grouped_data.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/430
> fix: align engine behavior for pivot

- Makefile
- setup.py
To help with flaky DuckDB behavior.
> chore: add pytest retry

- docs/bigquery.md
- docs/snowflake.md
- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Fixes: https://github.com/eakmanrq/sqlframe/issues/448
> feat: widen last/first value support

- sqlframe/base/column.py
- tests/integration/engines/test_engine_column.py
- tests/integration/engines/test_int_functions.py
- tests/unit/standalone/test_column.py
Resolves https://github.com/eakmanrq/sqlframe/pull/453
> fix: properly support endswith column func

- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Addresses some of https://github.com/eakmanrq/sqlframe/issues/460
> fix: duckdb array_distinct null support

- sqlframe/base/session.py
- sqlframe/base/util.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/467
> fix: make relativedelta option with duck typing

- sqlframe/base/util.py
- sqlframe/databricks/catalog.py
- sqlframe/databricks/readwriter.py
- sqlframe/duckdb/readwriter.py
- sqlframe/spark/readwriter.py
- tests/integration/engines/duck/test_duckdb_reader.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/469
> fix: duckdb sep argument

- sqlframe/base/session.py
- tests/integration/engines/duck/test_duckdb_session.py
- tests/unit/standalone/test_session.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/477
> feat: add session stop support

- setup.py
- sqlframe/base/dataframe.py
- sqlframe/base/operations.py
- sqlframe/base/util.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/476
Thanks @themattmorris for providing the fix. The rest of the PR was fixing another issue it identified while testing.
> fix: improve drop column

- setup.py
- sqlframe/base/dataframe.py
- sqlframe/base/util.py
Second try at resolving: https://github.com/eakmanrq/sqlframe/issues/476
This time doesn't also address the issue with overlapping select expressions.
> fix: improve drop v2

- Makefile
- sqlframe/base/dataframe.py
- sqlframe/base/mixins/table_mixins.py
- sqlframe/base/normalize.py
- tests/integration/fixtures.py
- tests/integration/test_int_dataframe.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/493
> feat: scope normalization to from clause

- docs/duckdb.md
- docs/snowflake.md
- sqlframe/base/functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/505
> feat: widen regexp_extract_all support

- docs/bigquery.md
- docs/duckdb.md
- docs/snowflake.md
- sqlframe/base/functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/508
> feat: widen transform/reduce/initcap support

- docs/bigquery.md
- docs/snowflake.md
- sqlframe/base/functions.py
- tests/integration/engines/test_int_functions.py
Resolves: https://github.com/eakmanrq/sqlframe/issues/517
> fix: support non-lambda functions
