sqlframe/base/dataframe.py
tests/unit/standalone/test_dataframe.py

Prior to this change there was a bug introduced by https://github.com/eakmanrq/sqlframe/pull/13 that if a compound where filter was provided only the last value was preserved.

fix: properly support compound filter expressions

---

sqlframe/base/dataframe.py
tests/unit/standalone/test_dataframe.py

Prior to this change if someone provided a column that had mixed case but their engine was case sensitive we wouldn't see this as a duplicate column name to replace the existing one and therefore create a duplicate column. This normalizes the value so the check should be correct now.

fix: normalize column names checking for matches

---

sqlframe/base/dataframe.py
sqlframe/base/normalize.py
tests/unit/standalone/test_dataframe.py

The operations decorator checks if there are two select operations in a row and if so it will convert the current leaf to a CTE. The issue is that when we don't use wrapped then column normalization occurs assuming a certain CTE structure but that could change doing the select since it goes through the decorator again. 
I think the real fix might be remove the double select check and converting to leaf logic but putting this in first since that might take a bit. 
Edit: Nevermind a double select should cause a rescoping.

fix: handle double column selects with dataframe lookup

---

docs/duckdb.md
docs/postgres.md
sqlframe/base/catalog.py
sqlframe/base/mixins/catalog_mixins.py
sqlframe/base/mixins/dataframe_mixins.py
sqlframe/bigquery/catalog.py
sqlframe/duckdb/catalog.py
sqlframe/duckdb/dataframe.py
sqlframe/postgres/catalog.py
sqlframe/postgres/dataframe.py
sqlframe/spark/catalog.py
tests/integration/engines/duck/test_duckdb_dataframe.py
tests/integration/engines/postgres/test_postgres_dataframe.py
tests/integration/engines/test_int_functions.py

Adds the ability to do "printSchema" in both DuckDB and Postgres.
The implementation works with engines that support temp views because they allow us to create a temp view and then get the view's data type from the information schema. BigQuery is not supported because it doesn't support temp views. A workaround is to create a temp table with limit 0/False like what we do in SQLMesh. The dataset it is created in is hidden and therefore will require an API call to get the column information. So a bit more involved so looking to do that later. 
Issue: https://github.com/eakmanrq/sqlframe/issues/25

feat: add printSchema support for duckdb and postgres

---

sqlframe/base/session.py
sqlframe/snowflake/session.py
tests/integration/engines/test_int_functions.py

Snowflake by default leaves variant types like arrays and dicts as strings instead of their python types. In order for this to work we had to disable arrow conversion on Snowflake. See this PR for more details and eventual support for arrow so we don't have to do this anymore: https://github.com/snowflakedb/snowflake-connector-python/issues/544
Related to: https://github.com/eakmanrq/sqlframe/issues/31
Video of me working on this: https://www.loom.com/share/945f5ad460f3475bb3a8ccce37d52ec3?sid=c16413b1-2ced-47b3-9c6b-1ec1d5a2f647

fix: Snowflake to properly convert variant types

---

docs/configuration.md
setup.py
sqlframe/base/dataframe.py
sqlframe/base/util.py

Adds the ability to use ChatGPT to enrich generated SQL in order to make it more like human SQL. The SQL used by SQLFrame when executing queries does not use optimization or ChatGPT so this just affects when a user calls `df.sql()` directly in order to see the generated SQL. 
Video: https://www.loom.com/share/3fab8493818b46f7bff03faf101d2bb6?sid=ba027a0c-4ab7-4531-a4f8-f1a95b70d7e6

feat: add openai enrichment support

---

setup.py

Prior to this the wheel for sqlframe wasn't including the typed files which are used to properly show what functions are available for each dataframe.

fix: properly include typing files

---

sqlframe/bigquery/functions.pyi
sqlframe/duckdb/functions.pyi
sqlframe/postgres/functions.pyi

`nullif` was already added but it just wasn't added to each engine's types.
PR where it was added: https://github.com/eakmanrq/sqlframe/pull/39

chore: add nullif to all engine types

---

sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py
tests/unit/standalone/test_dataframe.py

Add support for `withColumns`: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.withColumns.html
Related to: https://github.com/eakmanrq/sqlframe/issues/45

feat: add withColumns support

---

sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py
tests/unit/standalone/test_dataframe.py

Adds support for DataFrame `transform` method: https://spark.apache.org/docs/3.1.3/api/python/reference/api/pyspark.sql.DataFrame.transform.html
Related to: https://github.com/eakmanrq/sqlframe/issues/45

feat: add transform support

---

sqlframe/base/column.py
sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py

I checked the `column_expressions` for ambiguity but then later I just referred to the column itself for checking the name and updating the table reference. Now it consistently checks for the column_expression and the test was updated to properly verify this.
Fixes: https://github.com/eakmanrq/sqlframe/issues/50

fix: properly identify ambiguous column with an alias

---

sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py

Prior to this the code assumed that the columns in a select with ambiguous references were just column expressions but not it will search out all columns that might be ambiguous and therefore they can be more complex. 
Fixes: https://github.com/eakmanrq/sqlframe/issues/50

fix: select after join detect all possible columns

---

sqlframe/base/session.py

Potentially the more robust solution would be to parse the SparkConf object and check if it contains any SQLFrame related config but the documentation doesn't say this is supported and I wouldn't be surprised if not one does that so just ignoring for now. 
For Spark engine the conf object is passed through (method is overriden).

fix: ignore conf if passed in config

---

sqlframe/spark/catalog.py
tests/integration/engines/bigquery/test_bigquery_session.py

Databricks a future Spark releases could include more columns than SQLFrame currently supports so this limits what we use to just what is currently supported.

fix: support extra column properties when creating column object

---

docs/bigquery.md
docs/snowflake.md
sqlframe/base/dataframe.py
sqlframe/base/mixins/dataframe_mixins.py
sqlframe/bigquery/dataframe.py
sqlframe/duckdb/dataframe.py
sqlframe/postgres/dataframe.py
sqlframe/redshift/dataframe.py
sqlframe/snowflake/dataframe.py
sqlframe/spark/dataframe.py
tests/integration/engines/bigquery/test_bigquery_dataframe.py
tests/integration/engines/snowflake/test_snowflake_dataframe.py

Expands on https://github.com/eakmanrq/sqlframe/pull/29 and adds support for BQ and Snowflake.
Now all engines with a connection can get their current data types.

feat: add printSchema to BQ and Snowflake

---

README.md
docs/configuration.md
sqlframe/base/dataframe.py

When using `optimize`, invalid SQL can be generated. Therefore SQLFrame will now start favoring accurate SQL over readable by default but let user pass in `optimize=True` if they would like the optimized result.

feat: no longer optimize by default

---

README.md
blogs/add_chatgpt_support.md
blogs/sqlframe_universal_dataframe_api.md
docs/bigquery.md
docs/configuration.md

Now that inputs are parsed by default in spark format the catalog name needs to be quoted with double quotes (spark format) since it contains hyphens.

chore: fix example bq path

---

sqlframe/base/dataframe.py
sqlframe/duckdb/dataframe.py
tests/integration/engines/duck/test_duckdb_dataframe.py

Resolves: https://github.com/eakmanrq/sqlframe/issues/152
The PySpark API is very explicit in it's intention to load the full table in memory: https://spark.apache.org/docs/4.0.0-preview1/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.toArrow.html
For those using SQLFrame with DuckDB though it is a great feature to be able to batch up the result. Therefore SQLFrame adds a `batch_size` parameter to `toArrow` to support this. As noted this is not part of the PySpark API but SQLFrame is still backwards compatible with PySpark API so it seems fine.

feat: add arrow batching

---

sqlframe/duckdb/session.py
tests/common_fixtures.py
tests/integration/engines/duck/test_duckdb_catalog.py
tests/integration/engines/test_int_functions.py

This was supposed to be fixed in 1.1.0: https://github.com/duckdb/duckdb/pull/12790
It is unreliable though. Some CI tests would fail with `ERROR tests/integration/engines/duck/test_duckdb_catalog.py::test_set_current_catalog - duckdb.duckdb.InvalidInputException: Invalid Input Error: To set the TimeZone setting, the icu extension needs to be loaded. But it could not be autoloaded.`. Reverting back to old apporach. 
It seems like with 1.1.0 the settings put on a connection are not transferred to a cursor so also have to make sure that the connection is used insead of the new cursor object.

chore: adjust time zone approach back to legacy

---

sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py

Resolves: https://github.com/eakmanrq/sqlframe/issues/185
With the spark test it encounters a similar issue to https://github.com/eakmanrq/sqlframe/issues/184 where SQLFrame needs to have more awareness on how Spark deals with ambiguity and duplicate columns.

fix: allow joining same table twice

---

sqlframe/base/mixins/readwriter_mixins.py
sqlframe/base/readerwriter.py
sqlframe/duckdb/readwriter.py

Needed for compatibility purposes, simple implementation of these methods for available data sources (json and parquet)

Add missing format method and load method implementation

---

Makefile
docs/databricks.md
sqlframe/base/function_alternatives.py
sqlframe/base/functions.py
sqlframe/databricks/catalog.py
sqlframe/databricks/dataframe.py
sqlframe/databricks/functions.py
sqlframe/databricks/session.py
tests/common_fixtures.py
tests/integration/engines/databricks/test_databricks_catalog.py
tests/integration/engines/databricks/test_databricks_dataframe.py
tests/integration/engines/databricks/test_databricks_session.py
tests/integration/engines/test_engine_session.py
tests/integration/engines/test_int_functions.py
tests/integration/fixtures.py
tests/unit/databricks/test_activate.py

Hi,
I've added tests suport to the databricks backend and while doing it also fixed a couple of problems I've found.

Databricks tests

---

sqlframe/base/dataframe.py
tests/fixtures/issue_219.csv
tests/integration/engines/duck/test_duckdb_reader.py

Fixes: https://github.com/eakmanrq/sqlframe/issues/219
Since limit is last in the order of operations it should be fine to apply it directly to the query.

fix: remove convert to leaf before showing

---

sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py

fix: handle all 'how' values in df.join

---

docs/bigquery.md
docs/duckdb.md
docs/postgres.md
sqlframe/base/function_alternatives.py
sqlframe/base/functions.py

Resolves: https://github.com/eakmanrq/sqlframe/issues/259
This returns false which is confusing to me:
```
SELECT
REGEXP_LIKE('1a 2b 14m', '1') AS "REGEXP__STR__";
```
So just excluded Snowflake support for now. Might just be late and will make more sense to me another time.

feat: add regexp support except snowflake

---

Makefile
sqlframe/base/column.py
sqlframe/base/dataframe.py
sqlframe/base/functions.py
sqlframe/base/session.py
sqlframe/spark/session.py
tests/integration/engines/test_engine_dataframe.py
tests/integration/engines/test_int_functions.py
tests/integration/test_int_dataframe.py
tests/unit/standalone/test_dataframe.py
tests/unit/standalone/test_dataframe_writer.py
tests/unit/standalone/test_session_case_sensitivity.py

Resolves: https://github.com/eakmanrq/sqlframe/issues/258
PySpark, by default, is case-insensitive. Meaning if I have a mixed case column that I create I can reference that throughout my DataFrame code with any case. The unique part is that the mixed case will show up in the result to the user. Therefore a SQL-way to think about this is that the case provided by the user is not included in the SQL logic until the final select and is used to alias the final select columns to the case-sensitivity provided. 
Therefore SQLFrame calls this the `display_name` and now matches this behavior.

feat: support pyspark display name

---

sqlframe/base/session.py
tests/integration/test_int_dataframe.py

This PR adds the possibility to create a DataFrame from a `pd.DataFrame` using `session.createDataFrame`, further mimicking pyspark's behaviour"

feat!: accept pd.DataFrame in session.createDataFrame

---

docs/duckdb.md
sqlframe/base/util.py
tests/unit/test_util.py

Add support for converting to [`ByteType`](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.types.ByteType.html).
Documentation was already available in each backend/dialect.
Spotted on while trying to get schema in a narwhals test 😇

feat: add support for `ByteType`

---

docs/duckdb.md
docs/snowflake.md
sqlframe/base/function_alternatives.py
sqlframe/base/functions.py
tests/integration/engines/test_int_functions.py

Resolves: https://github.com/eakmanrq/sqlframe/issues/306

fix: have skewness match pyspark

---

sqlframe/base/catalog.py

I also did [this](https://github.com/eakmanrq/sqlframe/commit/30bc06603971a5815d54d6e16caf2a5e6db31621), but keep me honest on whether you want that, I'd be happy to remove that if need be. I had just encountered it when I passed a dummy table with no columns to `add_table`. You could reason that a table with no columns is worthless (and you'd be right), but I _think_ the intention of that truthy check was assuming None.
closes #313

feat: pass optional kwargs from `_BaseCatalog.add_table` to `sqlglot.MappingSchema.add_table`

---

sqlframe/base/util.py
sqlframe/duckdb/session.py

I believe this was old code that isn't needed anymore. Tested locally removing numpy and soundex worked fine without it.

fix: remove deprecated numpy check

---

sqlframe/base/dataframe.py
sqlframe/base/group.py
sqlframe/base/mixins/dataframe_mixins.py
sqlframe/base/operations.py
sqlframe/base/window.py

The goal of this PR is to provide typing support, VSCode autocomplete and doc-reference when using the standalone API. While all of the methods on `BaseDataFrame` already have nice signatures, these are erased by the `@operation`-decorator. This decorator preserves a functions signature, just adding some extra code around it. That makes `t.Callable[P, T]` the simplest type, where `P = ParamSpec("P")` represents arbitrary arguments (including kwargs) and `T = t.TypeVar("T")` some return type.
I opted for the more specific signature of `t.Callable[Concatenate[DF, P], T]`, which allows for typechecking the implementation of `@operation` itself. This decomposes into:
- The first parameter of the function is some DataFrame `DF = t.TypeVar("DF", bound=BaseDataFrame)`
- The remaining parameters …

Typing for DataFrame-Operations

---

sqlframe/base/function_alternatives.py
sqlframe/base/functions.py

Adds support for [DuckDB's `sha256` function](https://duckdb.org/docs/stable/sql/functions/utility.html#sha1string); compatible to [PySparks's `sha2` (numBits=256 or numBits=0)](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.sha2.html)

feat: add support sha2 for DuckDB

---

sqlframe/base/functions.py

functions like `from_json()`, `schema_of_json()`, `to_csv()`, `schema_of_csv()` allow passing in a `options`-Dictionary.
Although [PySpark docs](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.from_json.html?highlight=options) specifies that the dict's values should be of type `str`, the values are also [casted explicitely to string](https://spark.apache.org/docs/latest/api/python/_modules/pyspark/sql/functions.html#from_json:~:text=return%20_invoke_function(%22from_json%22%2C%20_to_java_column(col)%2C%20schema%2C%20_options_to_str(options))).
This PR mimics this behavior.

feat: cast options to string

---

sqlframe/base/functions.py
sqlframe/duckdb/functions.pyi

Adds support for [DuckDB's `sha1` function](https://duckdb.org/docs/stable/sql/functions/utility.html#sha1string); compatible to [PySparks's `sha1`](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.sha1.html)

feat: add support `sha1` for DuckDB

---

sqlframe/base/dataframe.py
sqlframe/base/decorators.py
sqlframe/base/functions.py
tests/unit/standalone/test_functions.py

fixes #342 
I didn't see where `CALLING_CLASS` was being used and assumed perhaps it was something that was previously used? I also removed import `from __future__ import annotations` because I didn't see where it was necessary in this module, but let me know if you disagree with either of these changes.
Thanks for considering this submission!

refactor: use `functools.wrap` in `func_metadata` decorator

---

sqlframe/base/dataframe.py
tests/integration/engines/test_engine_dataframe.py
tests/integration/test_int_dataframe.py

`DataFrame.head()` and `DataFrame.first()` used to raise `IndexError: list index out of range`. PySpark returns `None`.

fix: `df.head()` and `df.first()` on empty `DataFrame`

---

sqlframe/base/dataframe.py
tests/integration/engines/test_engine_dataframe.py
tests/integration/test_int_dataframe.py

Support for [pyspark.sql.DataFrame.isEmpty()](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.isEmpty.html)
Requires PR https://github.com/eakmanrq/sqlframe/pull/362 (fix for `DataFrame.head()`).

feat: add `DataFrame.isEmpty()`

---

sqlframe/duckdb/session.py

fixes #380 
Not sure when `InvalidInputException` got introduced in duckdb though. Tested with ddb 1.2.0 and 1.2.2.
How many old duckdb versions to you support?

handle InvalidInputException from duckdb when numpy is not installed

---

docs/bigquery.md
docs/duckdb.md
docs/postgres.md
docs/snowflake.md
sqlframe/base/functions.py
tests/integration/engines/test_int_functions.py
tests/unit/standalone/test_functions.py

Resolves: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.try_divide.html

feat: have try_divide support all engines

---

mkdocs.yml

Databricks is no longer considered in development so update the docs to reflect that. Also move configuration after overview since its hard to identify otherwise.

fix: update docs db no longer in dev

---

sqlframe/base/functions.py
tests/integration/engines/test_int_functions.py

Resolves: https://github.com/eakmanrq/sqlframe/issues/480
Addresses one of the issues in https://github.com/eakmanrq/sqlframe/issues/474

fix: handle timestamp type unix timestamp functions

---

sqlframe/base/dataframe.py
tests/integration/test_int_dataframe.py
tests/unit/standalone/test_dataframe.py

Resolves: #502
Enables:
```python
from sqlframe import standalone
from sqlframe.base import functions as f
spark = standalone.StandaloneSession()
df = spark.createDataFrame([{"foo": 0, "bar": "a"}, {"foo": 1, "bar": "b"}]).alias("df")
print(df.alias("df").select(f.col("df.foo"), f.col("df.bar")).groupBy(f.col("df.foo")).count().sql())
```
```sql
SELECT
CAST(`a1`.`foo` AS BIGINT) AS `foo`,
COUNT(*) AS `count`
FROM VALUES
(0, 'a'),
(1, 'b') AS `a1`(`foo`, `bar`)
GROUP BY
CAST(`a1`.`foo` AS BIGINT)
```

fix: allow dataframe aliases to be provided to groupBy columns
